[build]
  base = ""
  publish = "frontend/build"
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  functions = "backend"  # points to backend/lambda.js

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/lambda/:splat"
  status = 200
