[build]
base = "frontend"
publish = "build"
command = "npm install && npm run build"
functions = "../backend"  # relative to base = frontend

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/lambda/:splat"
status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
