[build]
  base = ""
  publish = "frontend/build"
  command = "npm install --prefix frontend && npm install --prefix backend && npm run build --prefix frontend"
  functions = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/lambda/:splat"
  status = 200
